Update test submodule and rearrange the order of pre-push

diff --git a/tool/reftest/pre-push b/tool/reftest/pre-push
--- a/tool/reftest/pre-push
+++ b/tool/reftest/pre-push
@@ -8,6 +8,13 @@ if cat error_report | grep 'ERROR'; then
  exit 1
 fi
 
+echo "checking... make internal_test"
+make internal_test > prepush_test_result
+if cat prepush_test_result |grep 'FAIL'; then
+ echo "$RED[FAIL] make internal_test$RESET"
+ exit 1
+fi
+
 echo "checking... make regression_test_blink_fast_dom"
 make regression_test_blink_fast_dom > prepush_test_result
 if cat prepush_test_result |grep 'FAIL'; then
@@ -154,13 +161,6 @@ echo "checking... make font_dependent_test_css"
 make font_dependent_test_css > prepush_test_result 2>&1
 if cat prepush_test_result |grep 'FAIL'; then
  echo "$RED[FAIL] make font_dependent_test_css$RESET"
- exit 1
-fi
-
-echo "checking... make internal_test"
-make internal_test > prepush_test_result
-if cat prepush_test_result |grep 'FAIL'; then
- echo "$RED[FAIL] make internal_test$RESET"
  exit 1
 fi
 
