Update tool/reftest/pre-push

diff --git a/tool/reftest/pre-push b/tool/reftest/pre-push
--- a/tool/reftest/pre-push
+++ b/tool/reftest/pre-push
@@ -8,59 +8,10 @@ if cat error_report | grep 'ERROR'; then
  exit 1
 fi
 
-echo "checking... make regression_test_dom_conformance_test"
-make regression_test_dom_conformance_test > prepush_test_result
-if cat prepush_test_result |grep 'FAIL'; then
- echo "$RED[FAIL] make regression_test_dom_conformance_test$RESET"
- exit 1
-fi
-
-echo "checking... make regression_test_webkit_dom_conformance_test"
-make regression_test_webkit_dom_conformance_test > prepush_test_result
-if cat prepush_test_result |grep 'FAIL'; then
- echo "$RED[FAIL] make regression_test_webkit_dom_conformance_test$RESET"
- exit 1
-fi
-
-echo "checking... make regression_test_blink_dom_conformance_test"
-make regression_test_blink_dom_conformance_test > prepush_test_result
-if cat prepush_test_result |grep 'FAIL'; then
- echo "$RED[FAIL] make regression_test_blink_dom_conformance_test$RESET"
- exit 1
-fi
-
-echo "checking... make regression_test_gecko_dom_conformance_test"
-make regression_test_gecko_dom_conformance_test > prepush_test_result
-if cat prepush_test_result |grep 'FAIL'; then
- echo "$RED[FAIL] make regression_test_gecko_dom_conformance_test$RESET"
- exit 1
-fi
-
-echo "checking... make regression_test_wpt_dom"
-make regression_test_wpt_dom > prepush_test_result
-if cat prepush_test_result |grep 'FAIL'; then
- echo "$RED[FAIL] make regression_test_wpt_dom$RESET"
- exit 1
-fi
-
-echo "checking... make regression_test_webkit_fast_dom"
-make regression_test_webkit_fast_dom > prepush_test_result
-if cat prepush_test_result |grep 'FAIL'; then
- echo "$RED[FAIL] make regression_test_webkit_fast_dom$RESET"
- exit 1
-fi
-
 echo "checking... make regression_test_blink_fast_dom"
 make regression_test_blink_fast_dom > prepush_test_result
 if cat prepush_test_result |grep 'FAIL'; then
  echo "$RED[FAIL] make regression_test_blink_fast_dom$RESET"
- exit 1
-fi
-
-echo "checking... make regression_test_wpt_html"
-make regression_test_wpt_html > prepush_test_result
-if cat prepush_test_result |grep 'FAIL'; then
- echo "$RED[FAIL] make regression_test_wpt_html$RESET"
  exit 1
 fi
 
@@ -70,6 +21,22 @@ if cat prepush_test_result |grep 'FAIL'; then
  echo "$RED[FAIL] make regression_test_blink_fast_html$RESET"
  exit 1
 fi
+
+echo "checking... make regression_test_blink_fast_css"
+make regression_test_blink_fast_css > prepush_test_result
+if cat prepush_test_result |grep 'FAIL'; then
+ echo "$RED[FAIL] make regression_test_blink_fast_css$RESET"
+ exit 1
+fi
+
+echo "checking... make regression_test_blink_fast_etc"
+make regression_test_blink_fast_etc > prepush_test_result
+if cat prepush_test_result |grep 'FAIL'; then
+ echo "$RED[FAIL] make regression_test_blink_fast_etc$RESET"
+ exit 1
+fi
+
+
 
 echo "checking... make regression_test_webkit_fast_html"
 make regression_test_webkit_fast_html > prepush_test_result
@@ -89,6 +56,27 @@ echo "checking... make regression_test_webkit_fast_etc"
 make regression_test_webkit_fast_etc > prepush_test_result
 if cat prepush_test_result |grep 'FAIL'; then
  echo "$RED[FAIL] make regression_test_webkit_fast_etc$RESET"
+ exit 1
+fi
+
+echo "checking... make regression_test_webkit_fast_dom"
+make regression_test_webkit_fast_dom > prepush_test_result
+if cat prepush_test_result |grep 'FAIL'; then
+ echo "$RED[FAIL] make regression_test_webkit_fast_dom$RESET"
+ exit 1
+fi
+
+echo "checking... make regression_test_wpt_dom"
+make regression_test_wpt_dom > prepush_test_result
+if cat prepush_test_result |grep 'FAIL'; then
+ echo "$RED[FAIL] make regression_test_wpt_dom$RESET"
+ exit 1
+fi
+
+echo "checking... make regression_test_wpt_html"
+make regression_test_wpt_html > prepush_test_result
+if cat prepush_test_result |grep 'FAIL'; then
+ echo "$RED[FAIL] make regression_test_wpt_html$RESET"
  exit 1
 fi
 
@@ -117,6 +105,34 @@ echo "checking... make regression_test_wpt_xhr"
 make regression_test_wpt_xhr > prepush_test_result
 if cat prepush_test_result |grep 'FAIL'; then
  echo "$RED[FAIL] make regression_test_wpt_xhr$RESET"
+ exit 1
+fi
+
+echo "checking... make regression_test_dom_conformance_test"
+make regression_test_dom_conformance_test > prepush_test_result
+if cat prepush_test_result |grep 'FAIL'; then
+ echo "$RED[FAIL] make regression_test_dom_conformance_test$RESET"
+ exit 1
+fi
+
+echo "checking... make regression_test_webkit_dom_conformance_test"
+make regression_test_webkit_dom_conformance_test > prepush_test_result
+if cat prepush_test_result |grep 'FAIL'; then
+ echo "$RED[FAIL] make regression_test_webkit_dom_conformance_test$RESET"
+ exit 1
+fi
+
+echo "checking... make regression_test_blink_dom_conformance_test"
+make regression_test_blink_dom_conformance_test > prepush_test_result
+if cat prepush_test_result |grep 'FAIL'; then
+ echo "$RED[FAIL] make regression_test_blink_dom_conformance_test$RESET"
+ exit 1
+fi
+
+echo "checking... make regression_test_gecko_dom_conformance_test"
+make regression_test_gecko_dom_conformance_test > prepush_test_result
+if cat prepush_test_result |grep 'FAIL'; then
+ echo "$RED[FAIL] make regression_test_gecko_dom_conformance_test$RESET"
  exit 1
 fi
 
