Apply parallel testing for bidi tests
Add bidi regression test to pre-push script

diff --git a/tool/reftest/pre-push b/tool/reftest/pre-push
--- a/tool/reftest/pre-push
+++ b/tool/reftest/pre-push
@@ -106,4 +106,11 @@ if cat prepush_test_result |grep 'FAIL'; then
  exit 1
 fi
 
+echo "checking... make regression_test_bidi"
+make regression_test_bidi > prepush_test_result
+if cat prepush_test_result |grep 'FAIL'; then
+ echo "$RED[FAIL] make regression_test_wpt_bidi$RESET"
+ exit 1
+fi
+
 rm prepush_test_result
