Add `regression_test_webkit_fast_css`

diff --git a/tool/reftest/pre-push b/tool/reftest/pre-push
--- a/tool/reftest/pre-push
+++ b/tool/reftest/pre-push
@@ -78,6 +78,13 @@ if cat prepush_test_result |grep 'FAIL'; then
  exit 1
 fi
 
+echo "checking... make regression_test_webkit_fast_css"
+make regression_test_webkit_fast_css > prepush_test_result
+if cat prepush_test_result |grep 'FAIL'; then
+ echo "$RED[FAIL] make regression_test_webkit_fast_css$RESET"
+ exit 1
+fi
+
 echo "checking... make regression_test_wpt_dom_events"
 make regression_test_wpt_dom_events > prepush_test_result
 if cat prepush_test_result |grep 'FAIL'; then
