Update pixel_test script : modify nw path update hook : uncomment regression_test_bidi, add pixel_test clean up make-tidy

diff --git a/tool/reftest/pre-push b/tool/reftest/pre-push
--- a/tool/reftest/pre-push
+++ b/tool/reftest/pre-push
@@ -106,12 +106,19 @@ if cat prepush_test_result |grep 'FAIL'; then
  exit 1
 fi
 
-#echo "checking... make regression_test_bidi"
-#make regression_test_bidi > prepush_test_result
-#if cat prepush_test_result |grep 'FAIL'; then
-# echo "$RED[FAIL] make regression_test_wpt_bidi$RESET"
-# exit 1
-#fi
+echo "checking... make regression_test_bidi"
+make regression_test_bidi > prepush_test_result
+if cat prepush_test_result |grep 'FAIL'; then
+ echo "$RED[FAIL] make regression_test_wpt_bidi$RESET"
+ exit 1
+fi
+
+echo "checking... make pixel_test_css_all"
+make pixel_test_css_all > prepush_test_result 2>&1
+if cat prepush_test_result |grep 'Error 1'; then
+ echo "$RED[FAIL] make pixel_test_css_all$RESET"
+ exit 1
+fi
 
 echo "checking... make internal_test"
 make internal_test > prepush_test_result
